# Generated by Django 4.2.5 on 2023-10-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='responseReply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_reply', to='board.response'),
        ),
    ]
